### ISSUE TITLE
socks5 proxy is used grequests returns None

### ISSUE THREAD

**Issue by themidnightoil** [kennethreitz/grequests#107]
```
    proxies = {
        "http": 'socks5://...',
        "https": 'socks5://...'

    }
    rs = (grequests.get(url,proxies = proxies) for url in urls)
    responses = grequests.map(rs)
    print(responses)
```

returns 
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None.,.,.,]

**Comment by mdomans** [comment]
Same problem here, though using crawlera as a proxy.

**Comment by spyoungtech** [comment]
Was not able to reproduce this issue testing in a number of situations. 

```python
In [19]: urls = ['https://httpbin.org/delay/2' for _ in range(10)]

In [20]: req_list = [grequests.get(url, proxies=proxies) for url in urls]

In [21]: result = grequests.map(req_list)

In [22]: result
Out[22]:
[<Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>]
```

**Comment by spyoungtech** [comment]
If this is still an issue, try adding an exception handler and provide the applicable exception. I don't think this is an issue caused directly by grequests.

**Comment by jonleach445** [comment]
I'm having same issue
