### ISSUE TITLE
Installed grequest cause Pycharm debug mode run error

### ISSUE THREAD

**Issue by muxi2015** [kennethreitz/grequests#121]
python ver: python 36
software ver: Pycharm 2017 2.3

**Comment by spyoungtech** [comment]
Hi @muxi2015 thanks for the report. Can you please provide some details (like error messages) on this and describe minimal steps to reproduce?

I am using PyCharm Professional 2.3 with Python 3.6 as well, but haven't had any problems installing grequests.

**Comment by muxi2015** [comment]
reproduce the problem:Pycharm debug django application

**Comment by carsonip** [comment]
In Settings > Build, Execution, Deployment > Python Debugger: check Gevent compatible
