### ISSUE TITLE
Is grequests deprecated?

### ISSUE THREAD

**Issue by jpthompson23** [kennethreitz/grequests#124]
Your note suggests using requests-threads or requests-futures instead. requests-futures requires Python 3, so it's not a solution for people using Python 2.7. And the readme for requests-threads says that its API is likely to change. If I want a stable API that works with Python 2.7, then it sounds like grequests is what I should be using.  But your note is confusing me -- is it saying that grequests is deprecated?  If grequests is not deprecated, I would like the note to be more clear and say so.

**Comment by kennethreitz** [comment]
If it works for you, it works for you — but this is not an actively maintained library.

**Comment by kennethreitz** [comment]
I much prefer Requests-Threads personally.
