### ISSUE TITLE
ImportError: No module named queue/Requests stop returning data

### ISSUE THREAD

**Issue by david193** [kennethreitz/grequests#4]
I wrote a test in which I use grequests to do a GET on my server 1000 times (throttled back to four simultaneous requests). The first 250 requests work fine, and then they stop returning data (and run very fast). Just before the run ends (after 995 of 1000 GETs), grequests raises this exception:

<pre>
Traceback (most recent call last):
  File "submit_test.py", line 32, in <module>
  File "submit_test.py", line 30, in main
  File "/Users/davidp/.virtualenvs/ssk_test/lib/python2.7/site-packages/grequests-0.1.0-py2.7.egg/grequests.py", line 83, in map
  File "/Users/davidp/.virtualenvs/ssk_test/lib/python2.7/site-packages/gevent-0.13.7-py2.7-macosx-10.6-intel.egg/gevent/greenlet.py", line 487, in joinall
ImportError: No module named queue
</pre>

I saw this same behavior with requests.async. It's not just my server because I get the same response when I use other sites. 

My test was run with Python 2.7.3 on Mac OS X 10.7.4. grequests 0.1.0. gevent 0.13.7.

Here is my test code:

<pre>
import time
import grequests

url = 'http://ssk-dev.appspot.com/test_service/default/search_unique'

def process_page (content, account_id):
    global start
    if content:
        length = len(content)
    else:
        length = 0
    print "In parse_page(): %d %d %f" % (account_id, length, time.time() - start)

def main ():
    global start
    start = time.time()
    
    # Make a list of callback functions 
    callback_list = []
    for i in range (1000):
        def wrapper (id = i):  # Fashion a closure because I need a bit of state
            def callback (response):
                process_page (response.content, id)
            return callback
        func = wrapper (i)
        callback_list.append (func)

    async_request_list = [grequests.get (url, hooks = {'response': func})
                                for func in callback_list]

    grequests.map (async_request_list, size = 4)

main()
</pre>

**Comment by fcamel** [comment]
I have similar issues with gevent=0.13.6 and requests=2.2.1

I suspect it is a bug in CPython and can workaround this by modifying gevent/greenlet.py. Just move ```from gevent.queue import Queue``` from ```def joinall()``` to the global space.

Here is my test codes:
```
import grequests

def exception_handler(request, exception):
    print "Request failed: %s" % exception

url = '...'
rs = [grequests.post(url, data={...}) for i in range(20000)]
rss = grequests.map(rs, size=5000, exception_handler=exception_handler)
```

Before running this, I increase the open file to 50000 to avoid "too many open files" error.
