### ISSUE TITLE
HEAD follows redirects

### ISSUE THREAD

**Issue by wearpants** [kennethreitz/grequests#45]
Per the plain-old requests documentation, redirects are followed for all requests *except* HEAD: http://docs.python-requests.org/en/latest/user/quickstart/#redirection-and-history

However, grequests follows redirects on HEAD unless explicitly told not to:

```
>>> bad=grequests.map([grequests.head('http://github.com')])[0]
>>> bad.status_code
200
>>> bad.history
(<Response [301]>,)
>>> bad.url
u'https://github.com/'


>>> good=grequests.map([grequests.head('http://github.com', allow
_redirects=False)])[0]
>>> good.status_code
301
>>> good.history
[]
>>> good.url
u'http://github.com/'
```

**Comment by kennethreitz** [comment]
HEAD should not redirect.
