### ISSUE TITLE
Cut a new 0.3.0 release :)

### ISSUE THREAD

**Issue by koobs** [kennethreitz/grequests#48]
test fix for requests hook kwargs [1] is handy for packagers / porters (QA) , along with the test_suite and tests_require changes [2]

[1] https://github.com/kennethreitz/grequests/commit/f50782ad63607b85e5e009f4a0a4ce0a8a6aef0d
[2] https://github.com/kennethreitz/grequests/pull/47

**Comment by starcroce** [comment]
+1 for new release
and when will be this new release? exception handling is really important to my project

**Comment by tristan0x** [comment]
Yes, please! a release! :raised_hands:

**Comment by dialt0ne** [comment]
+ 1 for new release w/exception handling

**Comment by ilyakamens** [comment]
+1 for new release w/ exception handling

**Comment by kennethreitz** [comment]
This will happen, very, very soon :)

Thanks for all the support! Good to know people still want this thing ;)

**Comment by kennethreitz** [comment]
Done!

**Comment by ilyakamens** [comment]
thank you!
