### ISSUE TITLE
Too many urls in greqests.map causes gevent.hub.LoopExit only on mac

### ISSUE THREAD

**Issue by mnowotka** [kennethreitz/grequests#50]
Detailed description is in this SO question: https://stackoverflow.com/questions/23117176/too-many-urls-in-greqests-map-causes-gevent-hub-loopexit-only-on-mac , but I will answer any questions in comments to this issue if needed.

**Comment by kennethreitz** [comment]
From SO: 

> It turned out that each request was executed in separate session. This was clearly not what I wanted so after solving this and sharing one session between all requests, the code is faster and doesn't give deadlocks anymore. On the other hand executing each requests in separate session should cause any problems (appart from being extremely inefficient) so thank you for the info.

May need to revisit that.
