### ISSUE TITLE
 map() got an unexpected keyword argument 'exception_handler'

### ISSUE THREAD

**Issue by legalimpurity** [kennethreitz/grequests#61]
i get this error  TypeError:map() got an unexpected keyword argument 'exception_handler'

i am getting it on this line

manresponse =grequests.map(rs,exception_handler = eception_handler)
 any help ??

**Comment by zoidbergwill** [comment]
Is there any chance of this getting a new release on pypi?

**Comment by nickflamel** [comment]
same error with grequest  0.2.0, python 2.7.10

**Comment by rtdean** [comment]
@nickflamel, there still hasn't been an official release with exception handling added into it.  You need to build from the master branch.

**Comment by kennethreitz** [comment]
Will be released shortly!
