### ISSUE TITLE
No response timeout exception throws AsyncRequest object has no attribute Exception

### ISSUE THREAD

**Issue by edfrenchtangentix** [kennethreitz/grequests#73]
Replicate:

url="http://www.google.com:81"# (chosen to cause no response)
item=grequests.get(url,hooks={'response':handle_result},timeout=20)
grequests.map(items, exception_handler=oops)

oops is not called but instead, eventually:

Traceback (most recent call last):
  File "C:\Users\edwar_000\Desktop\quickloadtest.py", line 54, in <module>
    grequests.map(async_list, exception_handler=oops)
  File "C:\Python27\lib\site-packages\grequests.py", line 123, in map
    exception_handler(request, request.exception)
AttributeError: 'AsyncRequest' object has no attribute 'exception'

**Comment by rtdean** [comment]
The latest release (presumably what you have installed) has a pretty serious bug in the exception handling code.  See PR #58 for a fix.

**Comment by kennethreitz** [comment]
Patch was merged! Release will be out shortly.
