### ISSUE TITLE
failed with SSLError

### ISSUE THREAD

**Issue by zuntah** [kennethreitz/grequests#79]
Hi

I also opened a question in stackoverflow:
http://stackoverflow.com/questions/34137147/grequests-python-async-http-requests-sslerror

this is the pastebin of the error:
http://pastebin.com/cjV6raJu

(NUM_OF_ASYNC_REQUESTS=20)

Thanks!

**Comment by zuntah** [comment]
<Greenlet at 0x3a3fdf0: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x039DD7D0>>(stream=False)> failed with SSLError

**Comment by zuntah** [comment]
Cant pase it here so im gonna use pastebin:
http://pastebin.com/cjV6raJu

**Comment by TaylorPaulSmith** [comment]
I'm experiencing this same issue.
