### ISSUE TITLE
Does it support callbacks ?

### ISSUE THREAD

**Issue by prakharjoshi** [kennethreitz/grequests#81]
Can we call some other function when a event is triggered ?

**Comment by kennethreitz** [comment]
Yep! You can pass `callback=some_function(request)` when creating an `AsyncRequest`.

**Comment by tokestermw** [comment]
I am getting `None` in my response with callbacks. Am I doing something wrong? Thanks.

```
>>> urls = ['http://www.heroku.com',
 'http://python-tablib.org',
 'http://httpbin.org',
 'http://python-requests.org',
 'http://kennethreitz.com']

>>> grequests.map([grequests.get(u) for u in urls])
[<Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>]

>>> callback = lambda x: x

>>> grequests.map([grequests.get(u, callback=callback) for u in urls])
[None, None, None, None, None]
```

**Comment by rtdean** [comment]
Callbacks is implemented in requests, see http://docs.python-requests.org/en/master/user/advanced/ for information.

Basically, the return value from your callback function becomes what you get in the output.  Since your callback returned None, you got None.  If you want the original response back, you need to return it.

**Comment by tokestermw** [comment]
`callback = lambda x: x` is returning `x`. But it seems to need a `**kwargs` to the function:

```
def callback(x, **kwargs):
    return x
```

**Comment by rtdean** [comment]
Actually, according to the requests documentation, the signature should be `response, *args, **kwargs`

So, to be correct to the docs...

```python
def callback(x, *args, **kwargs):
    return x
```

**Comment by LLCampos** [comment]
The callbacks are not working for me. I tried all the suggestions in this issue.

```python
>>> import grequests

>>> url_list = ['http://www.pythonforbeginners.com/system/python-sys-argv',
                'https://docs.python.org/2/howto/logging.html', 
                'https://stackoverflow.com/questions/576169/understanding-python-super-with-init-methods']

>>> grequests.map([grequests.get(url) for url in url_list])
[<Response [200]>, <Response [200]>, <Response [200]>]

>>> def callback1(response):
      return response.url

>>> grequests.map([grequests.get(url, callback=callback1) for url in url_list])
[None, None, None]

>>> def callback2(response, **kwargs):
      return response.url

>>> grequests.map([grequests.get(url, callback=callback1) for url in url_list])
[None, None, None]

>>> def callback3(response, *args, **kwargs):
      return response.url

>>> grequests.map([grequests.get(url, callback=callback3) for url in url_list])
[None, None, None]
```

**Comment by lormayna** [comment]
I have the same error.
Even if my callback return a list, the grequests.map is composed by None.
I'm at work now, but if you want I can provide some example.
