### ISSUE TITLE
Proposal of sample code (HttpJobXxx class with pre and post processing)

### ISSUE THREAD

**Issue by vlcinsky** [kennethreitz/grequests#87]
I have created [StackOverflow answer about using `grequests` with pre/post processing](http://stackoverflow.com/a/36813876/346478).

If you think, it would contribute to better understanding of `grequests`, feel free to include it into repository, modify as needed or let me know what form of pull request would be meeting your expectations.

**Comment by spyoungtech** [comment]
Nice writeup @vlcinsky -- I think you did a great job of walking through a good primary use case and demystifying some things that new users jumping into grequests may find useful.

As you noted, there is no rtd site documenting grequest's 153 lines of source code. I similarly discovered many possible patterns and features by reading the source. I think you and I would both agree the software does a great job of explaining itself. All that said, I personally would defer to @kennethreitz [advice for reasonable documentation](https://journal.kennethreitz.org/entry/documentation).

Keeping that in mind, I could see how the README might be improved with some concise additions. Maybe pull out what you feel is most useful or pertinent to include in the README and submit a PR and I'll be happy to take a look.

**Comment by vlcinsky** [comment]
@spyoungtech thanks for your feedback. Anyway, seeing 
> Note: You should probably use requests-threads or requests-futures instead.

in the existing `README.rst` I recon it is not worth investing my time into PR.

If you would ask me today, I would think of using [aiohttp](https://aiohttp.readthedocs.io/en/stable/)
