### ISSUE TITLE
grequests merge with requests

### ISSUE THREAD

**Issue by smorin** [kennethreitz/grequests#89]
@kennethreitz Is there any throughts on merging grequests back into the main, requests repo and or also adding support for Asynio/Trollius.   It's something I would be willing to work on if there was support from you as the founder/main developer for both projects.

Sorry for the comment here wasn't sure the best place to discuss this.

**Comment by kennethreitz** [comment]
grequests originated within the requests codebase as "requests.async". Many things have been extracted *out* of requests to make the core library as lean as possible, while providing all the hooks and correct abstractions to allow for these pieces to be provided by third-parties (see-also: oauth, kerberos auth).

**Comment by smorin** [comment]
Makes sense

**Comment by kennethreitz** [comment]
Closing — but more comments welcome!
