### ISSUE TITLE
Support for request throttling

### ISSUE THREAD

**Issue by withtwoemms** [kennethreitz/grequests#94]
Would be nice to be able to pass a `size` param to the `grequests.map` function to control the number of greenlets spawned at a given time.

**Comment by xennygrimmato** [comment]
Is there any update on this issue? @kennethreitz

**Comment by jontesek** [comment]
@withtwoemms It's merged, pls close the issue. 

https://github.com/kennethreitz/grequests/blob/master/grequests.py#L108
